// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Booking
{
    public int BookId { get; set; }

    public int? Pid { get; set; }

    public int? MovieId { get; set; }

    public DateOnly? BookingDate { get; set; }

    public int ShowId { get; set; }

    public string Status { get; set; }

    public int? Tid { get; set; }

    public int? UserId { get; set; }

    public string SeatNumbers { get; set; }

    public string ShowTime { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual Payment PidNavigation { get; set; }

    public virtual ShowTime Show { get; set; }

    public virtual Theater TidNavigation { get; set; }

    public virtual User User { get; set; }
}