// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("Booking")]
public partial class Booking
{
    [Key]
    [Column("BookID")]
    public int BookId { get; set; }

    public int? Pid { get; set; }

    [Column("MovieID")]
    public int? MovieId { get; set; }

    public DateOnly? BookingDate { get; set; }

    [Column("ShowID")]
    public int? ShowId { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public int? Tid { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("TicketID")]
    public int? TicketId { get; set; }

    [StringLength(50)]
    public string SeatNumbers { get; set; }

    [StringLength(50)]
    public string ShowTime { get; set; }

    [ForeignKey("MovieId")]
    [InverseProperty("Bookings")]
    public virtual Movie Movie { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("Bookings")]
    public virtual Payment PidNavigation { get; set; }

    [ForeignKey("TicketId")]
    [InverseProperty("Bookings")]
    public virtual Ticket Ticket { get; set; }

    [ForeignKey("Tid")]
    [InverseProperty("Bookings")]
    public virtual Theater TidNavigation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Bookings")]
    public virtual User User { get; set; }
}