// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Index("Pid", Name = "UQ__Cards__DD37D91B72EAB9D7", IsUnique = true)]
public partial class Card
{
    [Key]
    [Column("card_payment_id")]
    public int CardPaymentId { get; set; }

    [Column("pid")]
    public int Pid { get; set; }

    [Required]
    [Column("card_number_masked")]
    [StringLength(20)]
    [Unicode(false)]
    public string CardNumberMasked { get; set; }

    [Required]
    [Column("card_holder_name")]
    [StringLength(100)]
    [Unicode(false)]
    public string CardHolderName { get; set; }

    [Required]
    [Column("expiry_month")]
    [StringLength(2)]
    [Unicode(false)]
    public string ExpiryMonth { get; set; }

    [Required]
    [Column("expiry_year")]
    [StringLength(4)]
    [Unicode(false)]
    public string ExpiryYear { get; set; }

    [Required]
    [Column("card_type")]
    [StringLength(10)]
    [Unicode(false)]
    public string CardType { get; set; }

    [Required]
    [Column("card_cvv")]
    [StringLength(3)]
    [Unicode(false)]
    public string CardCvv { get; set; }

    [Column("transaction_id")]
    [StringLength(100)]
    [Unicode(false)]
    public string TransactionId { get; set; }

    [Column("payment_timestamp", TypeName = "datetime")]
    public DateTime? PaymentTimestamp { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("Card")]
    public virtual Payment PidNavigation { get; set; }
}