// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

public partial class CinePlusContext : DbContext
{
    public CinePlusContext()
    {
    }

    public CinePlusContext(DbContextOptions<CinePlusContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<MovieCast> MovieCasts { get; set; }

    public virtual DbSet<MovieLanguage> MovieLanguages { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ShowTime> ShowTimes { get; set; }

    public virtual DbSet<Theater> Theaters { get; set; }

    public virtual DbSet<Ticket> Tickets { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WKSBAN36SUHTR26\\SQLEXPRESS;Initial Catalog=CinePlus;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.AdminId).HasName("PK__Admin__719FE488B25F6154");

            entity.ToTable("Admin");

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookId).HasName("PK__Booking__3DE0C2277755786D");

            entity.ToTable("Booking");

            entity.Property(e => e.BookId).HasColumnName("BookID");
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.SeatNumbers).HasMaxLength(50);
            entity.Property(e => e.ShowId).HasColumnName("ShowID");
            entity.Property(e => e.ShowTime).HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Movie).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__Booking__MovieID__76969D2E");

            entity.HasOne(d => d.PidNavigation).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.Pid)
                .HasConstraintName("FK__Booking__Pid__75A278F5");

            entity.HasOne(d => d.TidNavigation).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.Tid)
                .HasConstraintName("FK__Booking__Tid__778AC167");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Booking__UserID__787EE5A0");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.CityId).HasName("PK__City__F2D21A961D9EFF72");

            entity.ToTable("City");

            entity.Property(e => e.CityId).HasColumnName("CityID");
            entity.Property(e => e.CityName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.GenreId).HasName("PK__Genre__0385055EFC0EB3C8");

            entity.ToTable("Genre");

            entity.Property(e => e.GenreId).HasColumnName("GenreID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.LanguageId).HasName("PK__Language__B938558B6B4053D8");

            entity.ToTable("Language");

            entity.Property(e => e.LanguageId).HasColumnName("LanguageID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.MovieId).HasName("PK__Movie__4BD2943A1DC1852B");

            entity.ToTable("Movie");

            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Duration).HasMaxLength(50);
            entity.Property(e => e.GenreId).HasColumnName("GenreID");
            entity.Property(e => e.MovieName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Genre).WithMany(p => p.Movies)
                .HasForeignKey(d => d.GenreId)
                .HasConstraintName("FK__Movie__GenreID__5165187F");
        });

        modelBuilder.Entity<MovieCast>(entity =>
        {
            entity.HasKey(e => e.Cid).HasName("PK__MovieCas__C1F8DC598802C121");

            entity.ToTable("MovieCast");

            entity.Property(e => e.Cid).HasColumnName("CID");
            entity.Property(e => e.Actor).HasMaxLength(100);
            entity.Property(e => e.Actress).HasMaxLength(100);
            entity.Property(e => e.Director).HasMaxLength(100);
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.Musician).HasMaxLength(100);
            entity.Property(e => e.Producer).HasMaxLength(100);

            entity.HasOne(d => d.Movie).WithMany(p => p.MovieCasts)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__MovieCast__Movie__5629CD9C");
        });

        modelBuilder.Entity<MovieLanguage>(entity =>
        {
            entity.HasKey(e => e.Mlid).HasName("PK__MovieLan__24F4D01D0577C85B");

            entity.ToTable("MovieLanguage");

            entity.Property(e => e.LanguageId).HasColumnName("LanguageID");
            entity.Property(e => e.MovieId).HasColumnName("MovieID");

            entity.HasOne(d => d.Language).WithMany(p => p.MovieLanguages)
                .HasForeignKey(d => d.LanguageId)
                .HasConstraintName("FK__MovieLang__Langu__628FA481");

            entity.HasOne(d => d.Movie).WithMany(p => p.MovieLanguages)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__MovieLang__Movie__619B8048");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__Payment__DD37D91AEC4A71E6");

            entity.ToTable("Payment");

            entity.Property(e => e.Pid)
                .ValueGeneratedNever()
                .HasColumnName("pid");
            entity.Property(e => e.PaymentType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("payment_type");
            entity.Property(e => e.ShowId).HasColumnName("show_id");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("total_amount");

            entity.HasOne(d => d.Show).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ShowId)
                .HasConstraintName("FK__Payment__show_id__72C60C4A");

            entity.HasOne(d => d.Ticket).WithMany(p => p.Payments)
                .HasForeignKey(d => d.Ticketid)
                .HasConstraintName("FK__Payment__Ticketi__71D1E811");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Review__74BC79AE8DD28AA3");

            entity.ToTable("Review");

            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.CommentText).HasMaxLength(255);
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.ShowId).HasColumnName("ShowID");
            entity.Property(e => e.Timings).HasMaxLength(50);

            entity.HasOne(d => d.Movie).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__Review__MovieID__5CD6CB2B");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.Uid)
                .HasConstraintName("FK__Review__Uid__5BE2A6F2");
        });

        modelBuilder.Entity<ShowTime>(entity =>
        {
            entity.HasKey(e => e.ShowId).HasName("PK__ShowTime__2B97D71C83A80BC8");

            entity.ToTable("ShowTime");

            entity.Property(e => e.ShowId)
                .ValueGeneratedNever()
                .HasColumnName("show_id");
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.Timings)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("timings");

            entity.HasOne(d => d.Movie).WithMany(p => p.ShowTimes)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__ShowTime__MovieI__6A30C649");
        });

        modelBuilder.Entity<Theater>(entity =>
        {
            entity.HasKey(e => e.Tid).HasName("PK__Theater__C456D729707202AA");

            entity.ToTable("Theater");

            entity.Property(e => e.Tid).HasColumnName("TID");
            entity.Property(e => e.CityId).HasColumnName("CityID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.City).WithMany(p => p.Theaters)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__Theater__CityID__59063A47");
        });

        modelBuilder.Entity<Ticket>(entity =>
        {
            entity.HasKey(e => e.Ticketid).HasName("PK__Ticket__712BC23F87BD47E6");

            entity.ToTable("Ticket");

            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.SeatNumbers).HasMaxLength(50);
            entity.Property(e => e.ShowId).HasColumnName("ShowID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Movie).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__Ticket__MovieID__6E01572D");

            entity.HasOne(d => d.Show).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.ShowId)
                .HasConstraintName("FK__Ticket__ShowID__6EF57B66");

            entity.HasOne(d => d.User).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Ticket__UserID__6D0D32F4");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CCACD4F58120");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__A9D105341FEA2573").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.MobileNo).HasMaxLength(15);
            entity.Property(e => e.Pass)
                .HasMaxLength(1)
                .HasColumnName("pass");
            entity.Property(e => e.SecurityAnswer)
                .HasMaxLength(1)
                .HasColumnName("Security_Answer");
            entity.Property(e => e.SecurityQuestion)
                .HasMaxLength(100)
                .HasColumnName("Security_Question");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}