// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

public partial class CinePlusContext : DbContext
{
    public CinePlusContext()
    {
    }

    public CinePlusContext(DbContextOptions<CinePlusContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Card> Cards { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<MovieCast> MovieCasts { get; set; }

    public virtual DbSet<MovieLanguage> MovieLanguages { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ShowTime> ShowTimes { get; set; }

    public virtual DbSet<Theater> Theaters { get; set; }

    public virtual DbSet<TheaterName> TheaterNames { get; set; }

    public virtual DbSet<Ticket> Tickets { get; set; }

    public virtual DbSet<Upi> Upis { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WKSBAN36SUHTR01\\SQLEXPRESS;Initial Catalog=CinePlus1;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.AdminId).HasName("PK__Admin__719FE4887FFEB327");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookId).HasName("PK__Booking__3DE0C227ECCB203C");

            entity.HasOne(d => d.Movie).WithMany(p => p.Bookings).HasConstraintName("FK__Booking__MovieID__7B5B524B");

            entity.HasOne(d => d.PidNavigation).WithMany(p => p.Bookings).HasConstraintName("FK__Booking__Pid__7A672E12");

            entity.HasOne(d => d.Ticket).WithMany(p => p.Bookings).HasConstraintName("FK__Booking__TicketI__7E37BEF6");

            entity.HasOne(d => d.TidNavigation).WithMany(p => p.Bookings).HasConstraintName("FK__Booking__Tid__7C4F7684");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings).HasConstraintName("FK__Booking__UserID__7D439ABD");
        });

        modelBuilder.Entity<Card>(entity =>
        {
            entity.HasKey(e => e.CardPaymentId).HasName("PK__Cards__8800A17979A5C414");

            entity.Property(e => e.CardCvv).IsFixedLength();
            entity.Property(e => e.ExpiryMonth).IsFixedLength();
            entity.Property(e => e.ExpiryYear).IsFixedLength();
            entity.Property(e => e.PaymentTimestamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.PidNavigation).WithOne(p => p.Card)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cards_Payment");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.CityId).HasName("PK__City__F2D21A966737C993");
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.GenreId).HasName("PK__Genre__0385055E604B6EEA");
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.LanguageId).HasName("PK__Language__B938558BF5370334");
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.MovieId).HasName("PK__Movie__4BD2943ADF983798");

            entity.HasOne(d => d.Genre).WithMany(p => p.Movies).HasConstraintName("FK__Movie__GenreID__534D60F1");
        });

        modelBuilder.Entity<MovieCast>(entity =>
        {
            entity.HasKey(e => e.Cid).HasName("PK__MovieCas__C1F8DC59696C2AD1");

            entity.HasOne(d => d.Movie).WithMany(p => p.MovieCasts).HasConstraintName("FK__MovieCast__Movie__5629CD9C");
        });

        modelBuilder.Entity<MovieLanguage>(entity =>
        {
            entity.HasKey(e => e.Mlid).HasName("PK__MovieLan__24F4D01DB300825B");

            entity.HasOne(d => d.Language).WithMany(p => p.MovieLanguages).HasConstraintName("FK__MovieLang__Langu__66603565");

            entity.HasOne(d => d.Movie).WithMany(p => p.MovieLanguages).HasConstraintName("FK__MovieLang__Movie__656C112C");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__Payment__DD37D91A3D5C71BB");

            entity.Property(e => e.PaymentDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("Ongoing");

            entity.HasOne(d => d.Movie).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payment_Movie");

            entity.HasOne(d => d.Show).WithMany(p => p.Payments).HasConstraintName("FK_Payment_ShowTime");

            entity.HasOne(d => d.Theater).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payment_Theater");

            entity.HasOne(d => d.Ticket).WithMany(p => p.Payments).HasConstraintName("FK_Payment_Ticket");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Review__74BC79AEE53C15C1");

            entity.HasOne(d => d.Movie).WithMany(p => p.Reviews).HasConstraintName("FK__Review__MovieID__60A75C0F");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.Reviews).HasConstraintName("FK__Review__Uid__5FB337D6");
        });

        modelBuilder.Entity<ShowTime>(entity =>
        {
            entity.HasKey(e => e.ShowId).HasName("PK__ShowTime__2B97D71C6AEA420D");

            entity.HasOne(d => d.Movie).WithMany(p => p.ShowTimes).HasConstraintName("FK__ShowTime__MovieI__693CA210");

            entity.HasOne(d => d.Theater).WithMany(p => p.ShowTimes).HasConstraintName("FK__ShowTime__Theate__6A30C649");
        });

        modelBuilder.Entity<Theater>(entity =>
        {
            entity.HasKey(e => e.Tid).HasName("PK__Theater__C456D72995FA7AEA");

            entity.HasOne(d => d.City).WithMany(p => p.Theaters).HasConstraintName("FK__Theater__CityID__59063A47");

            entity.HasOne(d => d.Movie).WithMany(p => p.Theaters).HasConstraintName("FK__Theater__MovieID__59FA5E80");
        });

        modelBuilder.Entity<TheaterName>(entity =>
        {
            entity.HasKey(e => e.Theaternameid).HasName("PK__TheaterN__46D68A3E2554AA90");

            entity.HasOne(d => d.City).WithMany(p => p.TheaterNames).HasConstraintName("FK__TheaterNa__CityI__5CD6CB2B");
        });

        modelBuilder.Entity<Ticket>(entity =>
        {
            entity.HasKey(e => e.Ticketid).HasName("PK__Ticket__712BC23F3E0E27BC");

            entity.HasOne(d => d.Movie).WithMany(p => p.Tickets).HasConstraintName("FK__Ticket__MovieID__6E01572D");

            entity.HasOne(d => d.Show).WithMany(p => p.Tickets).HasConstraintName("FK__Ticket__ShowID__6FE99F9F");

            entity.HasOne(d => d.Theater).WithMany(p => p.Tickets).HasConstraintName("FK__Ticket__TheaterI__6EF57B66");

            entity.HasOne(d => d.User).WithMany(p => p.Tickets).HasConstraintName("FK__Ticket__UserID__6D0D32F4");
        });

        modelBuilder.Entity<Upi>(entity =>
        {
            entity.HasKey(e => e.UpiPaymentId).HasName("PK__UPI__3939CBB8E3302C11");

            entity.Property(e => e.PaymentTimestamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.PidNavigation).WithOne(p => p.Upi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UPI_Payment");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CCAC68690CAA");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}