// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CinePlus.Models;

public partial class City
{
    public int CityId { get; set; }

    public string CityName { get; set; }

    [NotMapped]
    public DateTime? SelectedDate { get; set; }
    public virtual ICollection<Theater> Theaters { get; set; } = new List<Theater>();
}
