// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string MovieName { get; set; }

    public int? GenreId { get; set; }

    public string Duration { get; set; }

    public string Description { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public byte[] MoviePoster { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Genre Genre { get; set; }

    public virtual ICollection<MovieCast> MovieCasts { get; set; } = new List<MovieCast>();

    public virtual ICollection<MovieLanguage> MovieLanguages { get; set; } = new List<MovieLanguage>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<ShowTime> ShowTimes { get; set; } = new List<ShowTime>();

    public virtual ICollection<Theater> Theaters { get; set; } = new List<Theater>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}