// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Payment
{
    public int Pid { get; set; }

    public int? Ticketid { get; set; }

    public string Status { get; set; }

    public string PaymentType { get; set; }

    public decimal? TotalAmount { get; set; }

    public int? Showid { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ShowTime Show { get; set; }

    public virtual Ticket Ticket { get; set; }
}