// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? Uid { get; set; }

    public int? MovieId { get; set; }

    public int? Rating { get; set; }

    public string CommentText { get; set; }

    public int? Like { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User UidNavigation { get; set; }
}