// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Seat
{
    public int SeatId { get; set; }

    public string SeatNumber { get; set; }

    public int? TheaterId { get; set; }

    public virtual Theater Theater { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}