// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("ShowTime")]
public partial class ShowTime
{
    [Key]
    [Column("show_id")]
    public int ShowId { get; set; }

    [Column("MovieID")]
    public int? MovieId { get; set; }

    [Column("timings")]
    [StringLength(50)]
    [Unicode(false)]
    public string Timings { get; set; }

    public int? TheaterId { get; set; }

    [ForeignKey("MovieId")]
    [InverseProperty("ShowTimes")]
    public virtual Movie Movie { get; set; }

    [InverseProperty("Show")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("TheaterId")]
    [InverseProperty("ShowTimes")]
    public virtual Theater Theater { get; set; }

    [InverseProperty("Show")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}