// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

public partial class TheaterName
{
    [Key]
    [Column("TheaterName_Id")]
    public int TheaterNameId { get; set; }

    [Required]
    [Column("TheaterName")]
    [StringLength(100)]
    [Unicode(false)]
    public string TheaterName1 { get; set; }

    [Column("City_Id")]
    public int? CityId { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("TheaterNames")]
    public virtual City City { get; set; }
}