// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Theater
{
    public int Tid { get; set; }

    public string Name { get; set; }

    public int? CityId { get; set; }

    public decimal? Price { get; set; }

    public int? NoOfSeats { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual City City { get; set; }
}