// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Theatername
{
    public int Theaternameid { get; set; }

    public string Theatername1 { get; set; }

    public int? CityId { get; set; }

    public virtual City City { get; set; }
}