// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("TheaterName")]
public partial class TheaterName
{
    [Key]
    public int Theaternameid { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Theatername1 { get; set; }

    public int? CityId { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("TheaterNames")]
    public virtual City City { get; set; }
}