// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("Theater")]
public partial class Theater
{
    [Key]
    [Column("TID")]
    public int Tid { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("CityID")]
    public int? CityId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    public int? NoOfSeats { get; set; }

    public int? Movieid { get; set; }

    [InverseProperty("TidNavigation")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("CityId")]
    [InverseProperty("Theaters")]
    public virtual City City { get; set; }

    [ForeignKey("Movieid")]
    [InverseProperty("Theaters")]
    public virtual Movie Movie { get; set; }

    [InverseProperty("Theater")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Theater")]
    public virtual ICollection<Seat> Seats { get; set; } = new List<Seat>();

    [InverseProperty("Theater")]
    public virtual ICollection<ShowTime> ShowTimes { get; set; } = new List<ShowTime>();
}