// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class Ticket
{
    public int Ticketid { get; set; }

    public int? UserId { get; set; }

    public int? MovieId { get; set; }

    public string SeatNumbers { get; set; }

    public int? ShowId { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ShowTime Show { get; set; }

    public virtual User User { get; set; }
}