// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("Ticket")]
public partial class Ticket
{
    [Key]
    public int Ticketid { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("MovieID")]
    public int? MovieId { get; set; }

    [Column("ShowID")]
    public int? ShowId { get; set; }

    [Column("SeatID")]
    public int? SeatId { get; set; }

    [Column("Ticket_date", TypeName = "datetime")]
    public DateTime? TicketDate { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("MovieId")]
    [InverseProperty("Tickets")]
    public virtual Movie Movie { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("SeatId")]
    [InverseProperty("Tickets")]
    public virtual Seat Seat { get; set; }

    [ForeignKey("ShowId")]
    [InverseProperty("Tickets")]
    public virtual ShowTime Show { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Tickets")]
    public virtual User User { get; set; }
}