// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;
[Table("User")]
[Index("Username", Name = "UQ__User__536C85E4F763DECE", IsUnique = true)]
public partial class User
{
    public int UserId { get; set; }
    [Required(ErrorMessage = "Username is required. Please fill it.")]
    public string Username { get; set; }

    [Required(ErrorMessage = "Password is required. Please fill it.")]

    public byte[] Pass { get; set; }

    [Required(ErrorMessage = "Full Name is required. Please fill it.")]
    public string FullName { get; set; }

    [Required(ErrorMessage = "Age is required. Please fill it.")]
    [Range(18, 70, ErrorMessage = "Age must be between 18 and 70.")]
    public int? Age { get; set; }

    [Required(ErrorMessage = "Email is required. Please fill it.")]
    [EmailAddress(ErrorMessage = "Invalid email address format.")]
    [Key]
    public string Email { get; set; }

    [Required(ErrorMessage = "Gender is required. Please fill it.")]
    public string Gender { get; set; }

    [Required(ErrorMessage = "Mobile number is required. Please fill it.")]
    [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Mobile number must be 10 digits long.")]
    public string MobileNo { get; set; }
    [Required(ErrorMessage = "Address is required. Please fill it.")]
    public string Address { get; set; }
    public DateTime? CreatedAt { get; set; }
    public byte[] ProfilePic { get; set; }
    [Required(ErrorMessage = "Security question is required. Please fill it.")]
    public string Security_Question { get; set; }

    [Required(ErrorMessage = "Security answer is required. Please fill it.")]
    public string Security_Answer { get; set; }

    [NotMapped]
    public string Captcha { get; set; }
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}