// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CinePlus.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public byte[] Pass { get; set; }

    public string FullName { get; set; }

    public int? Age { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string MobileNo { get; set; }

    public string Address { get; set; }

    public DateTime? CreatedAt { get; set; }

    public byte[] ProfilePic { get; set; }

    public string SecurityQuestion { get; set; }

    public byte[] SecurityAnswer { get; set; }
    [NotMapped]
    public string Captcha { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}