// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class MovieCast
{
    public int? MovieId { get; set; }

    public int Cid { get; set; }

    public string Actor { get; set; }

    public string Actress { get; set; }

    public string Director { get; set; }

    public string Producer { get; set; }

    public string Musician { get; set; }

    public virtual Movie Movie { get; set; }
}