// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinePlus.Models;

public partial class MovieLanguage
{
    public int Mlid { get; set; }

    public int? MovieId { get; set; }

    public int? LanguageId { get; set; }

    public virtual Language Language { get; set; }

    public virtual Movie Movie { get; set; }
}