// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    [Column("pid")]
    public int Pid { get; set; }

    public int? Ticketid { get; set; }

    [Column("show_id")]
    public int? ShowId { get; set; }

    [Required]
    [Column("status")]
    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Required]
    [Column("payment_type")]
    [StringLength(20)]
    [Unicode(false)]
    public string PaymentType { get; set; }

    [Column("total_amount", TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    [Column("payment_date", TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [Column("Theater_id")]
    public int TheaterId { get; set; }

    [Column("Movie_id")]
    public int MovieId { get; set; }

    [Column("Seat_id")]
    public int SeatId { get; set; }

    [InverseProperty("PidNavigation")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("MovieId")]
    [InverseProperty("Payments")]
    public virtual Movie Movie { get; set; }

    [ForeignKey("SeatId")]
    [InverseProperty("Payments")]
    public virtual Seat Seat { get; set; }

    [ForeignKey("ShowId")]
    [InverseProperty("Payments")]
    public virtual ShowTime Show { get; set; }

    [ForeignKey("TheaterId")]
    [InverseProperty("Payments")]
    public virtual Theater Theater { get; set; }

    [ForeignKey("Ticketid")]
    [InverseProperty("Payments")]
    public virtual Ticket Ticket { get; set; }
}