// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CinePlus.Models;

[Table("Seat")]
public partial class Seat
{
    [Key]
    [Column("SeatID")]
    public int SeatId { get; set; }

    [Required]
    [StringLength(50)]
    public string SeatNumber { get; set; }

    [Column("TheaterID")]
    public int? TheaterId { get; set; }

    [InverseProperty("Seat")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("TheaterId")]
    [InverseProperty("Seats")]
    public virtual Theater Theater { get; set; }

    [InverseProperty("Seat")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}